"""nano-dsv4.1f educational DeepSeek-V4.1-Flash reference package."""

from .config import (
    AttentionConfig,
    CSA2Config,
    DSparkConfig,
    EngramConfig,
    IndexerConfig,
    IndexerTrainingConfig,
    ModelConfig,
    OptimizerConfig,
    ParallelismConfig,
    QuantizationConfig,
    RematConfig,
    RopeConfig,
    TrainConfig,
)
from .dspark import apply_dspark, sample_markov_block
from .model import apply_model, apply_model_dspark, build_layer_specs, init_model
from .optimizer import init_optimizer_state, optimizer_step, parameter_rule_map
from .tpu import (
    V5E,
    batch_named_sharding,
    compile_pretrain_step,
    init_model_sharded,
    init_optimizer_state_sharded,
    make_v5e_mesh,
    memory_report,
    parameter_partition_specs,
    put_training_batch,
    runtime_report,
    semantic_axes,
    validate_sequence_length,
    validate_v5e_runtime,
)
from .training import (
    build_indexer_groups,
    causal_lm_loss,
    indexer_phase_enabled,
    pretrain_loss,
    pretrain_step,
    selective_indexer_distillation_loss,
)

__all__ = [
    "AttentionConfig",
    "CSA2Config",
    "DSparkConfig",
    "EngramConfig",
    "IndexerConfig",
    "IndexerTrainingConfig",
    "ModelConfig",
    "OptimizerConfig",
    "ParallelismConfig",
    "QuantizationConfig",
    "RematConfig",
    "RopeConfig",
    "TrainConfig",
    "V5E",
    "apply_dspark",
    "apply_model",
    "apply_model_dspark",
    "batch_named_sharding",
    "build_indexer_groups",
    "build_layer_specs",
    "causal_lm_loss",
    "compile_pretrain_step",
    "indexer_phase_enabled",
    "init_model",
    "init_model_sharded",
    "init_optimizer_state",
    "init_optimizer_state_sharded",
    "make_v5e_mesh",
    "memory_report",
    "optimizer_step",
    "parameter_partition_specs",
    "parameter_rule_map",
    "pretrain_loss",
    "pretrain_step",
    "put_training_batch",
    "runtime_report",
    "sample_markov_block",
    "selective_indexer_distillation_loss",
    "semantic_axes",
    "validate_sequence_length",
    "validate_v5e_runtime",
]
