#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict, dataclass
import hashlib
import json
from pathlib import Path
import random
from typing import Any, Callable

from nano_dsv41f.agent_data import normalize_agent_trace
from nano_dsv41f.chat_protocol import (
    ASSISTANT_TOKEN,
    BOS_TOKEN,
    EOS_TOKEN,
    THINK_END_TOKEN,
    THINK_START_TOKEN,
    USER_TOKEN,
)
from nano_dsv41f.reasoning_effort import (
    assign_length_guided_reasoning_effort,
    missing_reasoning_efforts,
    reasoning_effort_histogram,
    render_v41_reasoning_effort_prompt,
    tokenizer_reasoning_length,
)


@dataclass(frozen=True)
class ReasoningSource:
    key: str
    dataset: str
    config: str | None
    split: str
    adapter: str
    license: str
    provenance: str


SOURCE_CATALOG: dict[str, ReasoningSource] = {
    "math": ReasoningSource(
        key="math",
        dataset="open-r1/OpenR1-Math-220k",
        config="default",
        split="train",
        adapter="openr1_math",
        license="apache-2.0",
        provenance=(
            "Problems from Apache-2.0 NuminaMath-1.5; reasoning traces generated by "
            "DeepSeek-R1 and verified upstream."
        ),
    ),
    "science": ReasoningSource(
        key="science",
        dataset="TianHongZXY/CHIMERA",
        config="Qwen3-235B-2507",
        split="train",
        adapter="chimera_science",
        license="apache-2.0",
        provenance=(
            "Fully synthetic CHIMERA rows; keep correctness=True and only Physics, "
            "Chemistry, or Biology. Solutions are generated by Qwen3-235B-A22B-Thinking-2507."
        ),
    ),
    "code": ReasoningSource(
        key="code",
        dataset="IIGroup/X-Coder-SFT-376k",
        config=None,
        split="verified_90k",
        adapter="xcoder",
        license="mit",
        provenance=(
            "Fully synthetic competitive-programming SFT data; use verified_90k, which "
            "the upstream dataset describes as all verified high-quality solutions."
        ),
    ),
}

DEFAULT_MIX = {"math": 0.45, "science": 0.30, "code": 0.25}
SCIENCE_SUBJECTS = frozenset({"Physics", "Chemistry", "Biology"})


def parse_mix(value: str) -> dict[str, float]:
    out: dict[str, float] = {}
    for piece in value.split(","):
        name, sep, weight = piece.partition(":")
        if not sep:
            raise ValueError("mix entries must be source:weight")
        key = name.strip()
        if key not in SOURCE_CATALOG:
            raise ValueError(f"unknown SFT source {key!r}; choose from {sorted(SOURCE_CATALOG)}")
        out[key] = float(weight)
    total = sum(out.values())
    if not out or any(weight <= 0 for weight in out.values()):
        raise ValueError("mix weights must be positive")
    if abs(total - 1.0) > 1e-9:
        raise ValueError(f"mix weights must sum to 1.0, got {total}")
    return out


def split_think_content(text: str) -> tuple[str, str] | None:
    start = text.find("<think>")
    if start < 0:
        return None
    end = text.find("</think>", start + len("<think>"))
    if end < 0:
        return None
    reasoning = text[start + len("<think>") : end].strip()
    prefix = text[:start].strip()
    suffix = text[end + len("</think>") :].strip()
    if not reasoning or not suffix:
        return None
    final = "\n".join(part for part in (prefix, suffix) if part)
    return reasoning, final


def _record(
    *,
    source: ReasoningSource,
    user: str,
    reasoning: str,
    final: str,
    metadata: dict[str, Any],
) -> dict[str, Any] | None:
    if not all(isinstance(x, str) and x.strip() for x in (user, reasoning, final)):
        return None
    return normalize_agent_trace(
        {
            "messages": [
                {"role": "user", "content": user.strip()},
                {
                    "role": "assistant",
                    "reasoning_content": reasoning.strip(),
                    "content": final.strip(),
                },
            ],
            "thinking_mode": "thinking",
            "metadata": {
                "dataset": source.dataset,
                "source": source.key,
                "upstream_license": source.license,
                **metadata,
            },
        },
        default_thinking_mode="thinking",
        default_reasoning_effort=50,
    )


def adapt_openr1_math(source: ReasoningSource, row: dict[str, Any]) -> dict[str, Any] | None:
    user = row.get("problem")
    if not isinstance(user, str) or not user.strip():
        messages = row.get("messages")
        if isinstance(messages, list) and messages and isinstance(messages[0], dict):
            user = messages[0].get("content")
    if not isinstance(user, str) or not user.strip():
        return None

    generations = row.get("generations")
    complete = row.get("is_reasoning_complete")
    math_verified = row.get("correctness_math_verify")
    llama_verified = row.get("correctness_llama")
    if not isinstance(generations, list) or not isinstance(complete, list):
        return None

    for i, generation in enumerate(generations):
        if i >= len(complete) or complete[i] is not True:
            continue
        math_ok = (
            isinstance(math_verified, list)
            and i < len(math_verified)
            and math_verified[i] is True
        )
        llama_ok = (
            isinstance(llama_verified, list)
            and i < len(llama_verified)
            and llama_verified[i] is True
        )
        if not (math_ok or llama_ok):
            continue
        if not isinstance(generation, str):
            continue
        split = split_think_content(generation)
        if split is None:
            continue
        reasoning, final = split
        return _record(
            source=source,
            user=user,
            reasoning=reasoning,
            final=final,
            metadata={
                "uuid": row.get("uuid"),
                "upstream_source": row.get("source"),
                "problem_type": row.get("problem_type"),
                "generation_index": i,
                "reasoning_complete": True,
                "math_verify": math_ok,
                "llama_verify": llama_ok,
            },
        )
    return None


def adapt_chimera_science(source: ReasoningSource, row: dict[str, Any]) -> dict[str, Any] | None:
    if row.get("correctness") is not True:
        return None
    subject = row.get("subject")
    if subject not in SCIENCE_SUBJECTS:
        return None
    return _record(
        source=source,
        user=row.get("question"),
        reasoning=row.get("solution"),
        final=row.get("answer"),
        metadata={
            "subject": subject,
            "topic": row.get("topic"),
            "index": row.get("index"),
            "correctness": True,
        },
    )


def adapt_xcoder(source: ReasoningSource, row: dict[str, Any]) -> dict[str, Any] | None:
    query, response = row.get("query"), row.get("response")
    if not isinstance(query, str) or not isinstance(response, str):
        return None
    split = split_think_content(response)
    if split is None:
        return None
    reasoning, final = split
    return _record(
        source=source,
        user=query,
        reasoning=reasoning,
        final=final,
        metadata={"upstream_split": source.split},
    )


ADAPTERS: dict[
    str, Callable[[ReasoningSource, dict[str, Any]], dict[str, Any] | None]
] = {
    "openr1_math": adapt_openr1_math,
    "chimera_science": adapt_chimera_science,
    "xcoder": adapt_xcoder,
}


def render_simple_v41_sft(case: dict[str, Any]) -> str:
    """Render the text-only two-turn subset used for the length gate."""
    messages = case["messages"]
    if (
        len(messages) != 2
        or messages[0]["role"] != "user"
        or messages[1]["role"] != "assistant"
    ):
        raise ValueError("simple renderer expects one user turn and one assistant turn")
    assistant = messages[1]
    reasoning = assistant.get("reasoning_content")
    if not isinstance(reasoning, str) or not reasoning:
        raise ValueError("thinking SFT record needs explicit reasoning_content")
    effort = int(case["reasoning_effort"])
    return (
        BOS_TOKEN
        + render_v41_reasoning_effort_prompt(effort)
        + USER_TOKEN
        + messages[0]["content"]
        + ASSISTANT_TOKEN
        + THINK_START_TOKEN
        + reasoning
        + THINK_END_TOKEN
        + assistant.get("content", "")
        + EOS_TOKEN
    )


def token_count(tokenizer, text: str) -> int:
    return len(tokenizer.encode(text, add_special_tokens=False).ids)


def core_token_count(tokenizer, case: dict[str, Any]) -> int:
    messages = case["messages"]
    return (
        token_count(tokenizer, messages[0]["content"])
        + token_count(tokenizer, messages[1]["reasoning_content"])
        + token_count(tokenizer, messages[1].get("content", ""))
        + 48
    )


def stable_case_digest(case: dict[str, Any]) -> bytes:
    payload = json.dumps(case["messages"], ensure_ascii=False, sort_keys=True)
    return hashlib.blake2b(payload.encode("utf-8"), digest_size=16).digest()


def load_stream(source: ReasoningSource, *, seed: int, shuffle_buffer: int):
    try:
        from datasets import load_dataset
    except ImportError as exc:
        raise SystemExit(
            "Reasoning SFT preparation needs datasets: pip install -e '.[data]'"
        ) from exc
    kwargs: dict[str, Any] = {
        "path": source.dataset,
        "split": source.split,
        "streaming": True,
    }
    if source.config is not None:
        kwargs["name"] = source.config
    return load_dataset(**kwargs).shuffle(seed=seed, buffer_size=shuffle_buffer)


def collect_source(
    source_key: str,
    *,
    target_tokens: int,
    tokenizer,
    max_tokens: int,
    seed: int,
    shuffle_buffer: int,
    seen: set[bytes],
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    source = SOURCE_CATALOG[source_key]
    adapter = ADAPTERS[source.adapter]
    stream = load_stream(source, seed=seed, shuffle_buffer=shuffle_buffer)

    cases: list[dict[str, Any]] = []
    accepted_tokens = 0
    seen_rows = 0
    dropped_adapter = 0
    dropped_too_long = 0
    dropped_duplicate = 0
    for row in stream:
        seen_rows += 1
        case = adapter(source, row)
        if case is None:
            dropped_adapter += 1
            continue
        digest = stable_case_digest(case)
        if digest in seen:
            dropped_duplicate += 1
            continue
        approx = core_token_count(tokenizer, case)
        if approx > max_tokens:
            dropped_too_long += 1
            continue
        seen.add(digest)
        cases.append(case)
        accepted_tokens += approx
        if accepted_tokens >= target_tokens:
            break

    if accepted_tokens < target_tokens:
        raise RuntimeError(
            f"{source_key} exhausted at {accepted_tokens:,} accepted tokens; "
            f"target was {target_tokens:,}"
        )
    return cases, {
        "rows_seen": seen_rows,
        "accepted": len(cases),
        "approx_tokens": accepted_tokens,
        "dropped_adapter_or_quality_filter": dropped_adapter,
        "dropped_too_long": dropped_too_long,
        "dropped_duplicate": dropped_duplicate,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Prepare license-auditable DeepSeek-V4.1-style reasoning SFT JSONL with "
            "integer reasoning_effort labels measured using the frozen nano tokenizer."
        )
    )
    parser.add_argument("--tokenizer", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--target-tokens", type=int, default=4_000_000)
    parser.add_argument("--max-tokens", type=int, default=4096)
    parser.add_argument(
        "--mix",
        default=",".join(f"{k}:{v}" for k, v in DEFAULT_MIX.items()),
        help="reasoning source keys and token weights",
    )
    parser.add_argument("--jitter", type=int, default=2)
    parser.add_argument("--seed", type=int, default=1701)
    parser.add_argument("--shuffle-buffer", type=int, default=5_000)
    args = parser.parse_args()

    if args.target_tokens <= 0 or args.max_tokens <= 0:
        raise SystemExit("token targets must be positive")
    mix = parse_mix(args.mix)

    try:
        from tokenizers import Tokenizer
    except ImportError as exc:
        raise SystemExit(
            "Reasoning SFT preparation needs tokenizers: pip install -e '.[data]'"
        ) from exc
    tokenizer = Tokenizer.from_file(str(args.tokenizer))
    args.output_dir.mkdir(parents=True, exist_ok=True)

    cases: list[dict[str, Any]] = []
    collection: dict[str, object] = {}
    seen: set[bytes] = set()
    for offset, (source_key, weight) in enumerate(mix.items()):
        target = round(args.target_tokens * weight)
        subset, stats = collect_source(
            source_key,
            target_tokens=target,
            tokenizer=tokenizer,
            max_tokens=args.max_tokens,
            seed=args.seed + 1009 * offset,
            shuffle_buffer=args.shuffle_buffer,
            seen=seen,
        )
        cases.extend(subset)
        collection[source_key] = {"target_tokens": target, **stats}
        print(source_key, stats)

    cases = assign_length_guided_reasoning_effort(
        cases,
        length_fn=tokenizer_reasoning_length(tokenizer),
        length_unit="tokens",
        jitter=args.jitter,
        seed=args.seed,
        preserve_existing=False,
    )

    filtered: list[dict[str, Any]] = []
    dropped_exact_length = 0
    for case in cases:
        rendered_tokens = token_count(tokenizer, render_simple_v41_sft(case))
        if rendered_tokens > args.max_tokens:
            dropped_exact_length += 1
            continue
        case["metadata"]["rendered_tokens"] = rendered_tokens
        filtered.append(case)
    cases = assign_length_guided_reasoning_effort(
        filtered,
        length_fn=tokenizer_reasoning_length(tokenizer),
        length_unit="tokens",
        jitter=args.jitter,
        seed=args.seed,
        preserve_existing=False,
    )

    final_cases: list[dict[str, Any]] = []
    for case in cases:
        rendered_tokens = token_count(tokenizer, render_simple_v41_sft(case))
        if rendered_tokens <= args.max_tokens:
            case["metadata"]["rendered_tokens"] = rendered_tokens
            final_cases.append(case)
        else:
            dropped_exact_length += 1
    cases = final_cases

    rng = random.Random(args.seed + 41)
    rng.shuffle(cases)
    output = args.output_dir / "reasoning_sft.jsonl"
    with output.open("w", encoding="utf-8") as f:
        for case in cases:
            f.write(json.dumps(case, ensure_ascii=False) + "\n")

    histogram = reasoning_effort_histogram(cases)
    total_rendered_tokens = sum(
        int(case["metadata"]["rendered_tokens"]) for case in cases
    )
    source_counts = Counter(str(case["metadata"].get("source")) for case in cases)
    manifest = {
        "format": "nano-dsv41f-reasoning-sft-v2",
        "mix": mix,
        "sources": {
            key: {
                **asdict(SOURCE_CATALOG[key]),
                "target_tokens": round(args.target_tokens * mix[key]),
                "collection": collection[key],
            }
            for key in mix
        },
        "selection": {
            "target_tokens": args.target_tokens,
            "max_rendered_tokens": args.max_tokens,
            "seed": args.seed,
            "dropped_after_exact_render_length": dropped_exact_length,
        },
        "reasoning_effort": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "method": "reasoning_length_percentile_v1",
            "jitter": args.jitter,
            "covered_values": sum(1 for count in histogram.values() if count),
            "missing_values": list(missing_reasoning_efforts(cases)),
            "histogram": histogram,
        },
        "output": {
            "records": len(cases),
            "rendered_tokens": total_rendered_tokens,
            "source_counts": dict(source_counts),
            "jsonl": output.name,
        },
    }
    (args.output_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        {
            "records": len(cases),
            "rendered_tokens": total_rendered_tokens,
            "effort_coverage": manifest["reasoning_effort"]["covered_values"],
            "output": str(output),
        }
    )


if __name__ == "__main__":
    main()
